fix(types): upgrade types of OpenLayers
An error occurred when you try to build the application due to wrong version of typings for OpenLayers. Some methods used in the StyleComponent object were not defined. The ngc build returned the following errors : 
```
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:60:21: Property 'setRadius' does not exist on type 'Circle'.
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:67:24: Property 'setImage' does not exist on type 'Style'.
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:73:43: Property 'setRadius' does not exist on type 'Circle'.
Error at /Users/kdavin/Workspace/Airbus/webfactory/angular-openlayers/src/components/style.components.ts:79:24: Property 'setImage' does not exist on type 'Style'.
```